### ISSUE TITLE
Defining action + events with the same name is forbidden

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#330]
Consider this example service which defines an action and respective events for it:

```yaml
actions:
  schedule:
    help: Schedule events
    http:
      path: /schedule
      method: post
      port: 8080
    arguments:
      name:
        type: string
        required: true
        in: requestBody
    output:
      type: none
    events:
      triggered:
        help: Subscribe to scheduled events
        http:
          port: 8080
          subscribe:
            path: /subscribe
            method: post
            contentType: application/json
        arguments:
          name:
            type: string
            in: requestBody
        output:
          type: object
          contentType: application/json
          properties:
            name:
              type: string
```

Currently, the validation forbids this:

```
  - .actions.event.http must be not defined when events is defined
```

Is there are reason for this?
